export * from './categoria.repository';
export * from './cuaderno-de-novedades.repository';
export * from './estado-ambiente.repository';
export * from './habitacion.repository';
export * from './persona.repository';
export * from './salon.repository';
export * from './tipo-persona.repository';
export * from './user-credentials.repository';
export * from './user.repository';
